### PR TITLE
Add issuer to tokens_issue op

### PR DESCRIPTION
**Pull request by Rishi556**

### CODE REVIEW

**Comment by bt-cryptomancer** [comment]
Looks good to me.

**Comment by forkyishere** [comment]
Shouldn't we be bumping the package.json version on these? I also like the qa merge branch method we use on the https://github.com/hive-engine/hivesmartcontracts one to test stuff.

**Comment by Rishi556** [comment]
@forkyishere dev branch is probably best done in a new repo whenever that's created. And yeah, a package.json version bump would be nice to keep track. @bt-cryptomancer

**Comment by forkyishere** [comment]
~~Will wait for you @Rishi556, to see if you can pass this (https://github.com/hive-engine/ssc_tokens_history/issues/26) or you can replicate.~~ Scratch this, unrelated with this PR.

**Pull request merged**
